### ISSUE TITLE
Blocked nodejs event loop during callback leads to error

### ISSUE THREAD

**Issue by leovin** [mika-fischer/napi-thread-safe-callback#5]
Hi,

I'm creating a wrapper for a library that has "pumping" mode for events.
In this mode, lib calls lot's of callbacks.

It looks like when nodejs is busy with something synchronous like "console.log()", callback can't make it with error:
Assertion failed: !(handle->flags & UV__HANDLE_CLOSING), file src\win\async.c, line 76
npm ERR! code ELIFECYCLE
npm ERR! errno 3221226505

Should be easy to reproduce in tests by calling callback multiple times in a loop while doing something synchronous in nodejs.

Could you please try to reproduce this issue?
In case it's a known limitation, what workaround options are available?

Thank you

**Comment by mika-fischer** [comment]
I can't reproduce this. Maybe you can adapt the test case in be7efa568e2a2ec1e023b07a4365b2094624f742 so that it fails for you?

**Comment by mika-fischer** [comment]
Oh, and the error message seems to indicate that `uv_async_send` is called on an `uv_async_t` handle that is already closed. So maybe the lifetime of the callback object matters. However, I'm having a hard time seeing how it's possible that `uv_async_send` is called after `ThreadSafeCallbacl::Impl::close`...

**Comment by leovin** [comment]
Thanks for taking a look.
Will try to reproduce using your test.

**Comment by leovin** [comment]
Can't reproduce on Mac at home, will try Windows at work tomorrow.
Looking at file from err "src\win\async.c" this issue might be specific to windows.

**Comment by leovin** [comment]
You were right: "the lifetime of the callback object matters".

Looks like V8 is garbage collecting JS callback.

Thank you!

**Comment by leovin** [comment]
Code that reproduces error:

// 1) set call back and start pumping events
const eventsLib = new addon.eventsLib()
eventsLib.pumpCallback = function() { console.log("JS") }
eventsLib.startPumping()

// 2) keep nodejs running
setInterval(() => {
    // eventsLib.pumpCallback = function() { console.log("JS") }
}, 1000)

In such case V8 will collect callback (even if it's a named const function).
When callback is uncommented in setInterval, everything works fine.

Will google how to pinpoint JS objects, if possible at all.

**Comment by mika-fischer** [comment]
Hm, strange. This should not happen unless the `ThreadSafeCallback` object is destroyed *and* the event loop got around to calling `uv_close` on the handle *and* the callback to `uv_close` is called, which finally releases the reference to the callback. But at that point, how is it possible that `ThreadSafeCallback::send` is called?

**Comment by leovin** [comment]
Maybe "eventsLib" (napi addon) gets collected, together with "eventsLib.pumpCallback".

**Comment by mika-fischer** [comment]
Possible, I was more thinking of the lifetime of the `ThreadSafeCallback` object. If the `eventsLib` object holds the `ThreadSafeCallback`, then this could explain, why `ThreadSafeCallback` is destroyed. But it still can't explain how after that point, `ThreadSafeCallback::send` can be called.

But without seeing the code, or having a self-contained example reproducing this, there's not much more I can do.

**Comment by leovin** [comment]
https://pastebin.com/4BCX9SPg

Please don't judge my c++ :)
I'm just a product manager doing POC.

**Comment by mika-fischer** [comment]
OK, I think there are two issues:

1) You should use a `std::unique_ptr` (or `std::shared_ptr`) to store the `CManagerInterface` pointer `mt`. That way, it is ensured that when `Mtmanapi` is destroyed, the `CManagerInterface` is destroyed as well. Currently it will outlive `Mtmanapi` and a) cause a leak and b) keep calling the callback, which now points to a `ThreadSafeCallback` object that has already been destroyed. Fixing this should fix the crash.

2) Then you need to figure out how to keep the `Mtmanapi` object alive because it really seems as if it's garbage collected currently. I don't think there's much that this lib can do to help, but if there is, please open another issue.

**Comment by leovin** [comment]
Thank you again for your help!

**Comment by leovin** [comment]
1. wrapping "mt" with "std::shared_ptr" https://pastebin.com/MRWMjY5f didn't change the error

2. solved by periodically calling one of Mtmanapi functions, because it looks like there's no way to explicitly control object lifetime in js

**Comment by mika-fischer** [comment]
You have a `shared_ptr` to a pointer, which is not very useful. The `CManagerInterface` is still not being cleaned up properly.

Line 166 should be `std::shared_ptr<CManagerInterface> mt;` and line 49 should be `mt.reset(mtFactory.Create(ManAPIVersion));`

For 2 it should suffice to just keep a reference to the eventsLib object around to keep the GC from collecting it.
